# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1748c6392996877e9523f0dfc729020292e50673224f4e17f30ae32a7aa735413817d87a0f76c132ac57589ebfdff9dbb485b6c872756b590dd80fcef9bac286

test:
  secret_key_base: 8a598294e59ef0013f625b77b9d814a4a7a3947f8c38562bc860e74c97a4bc3a568ed0a1a4549fae8d185aa0de44d5288c7ea995a6960475ebc02b19ffe5c270

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
